name: .NET Build Artifacts

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        rid: [linux-x64, win-x64]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish
        run: dotnet publish -c Release -r ${{ matrix.rid }} --self-contained false -o publish/${{ matrix.rid }}

      - name: Upload published binaries
        uses: actions/upload-artifact@v4
        with:
          name: published-${{ matrix.rid }}
          path: publish/${{ matrix.rid }}