name: .NET Build Artifacts

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  publish:
    runs-on: macos-latest
    strategy:
      matrix:
        rid: [linux-x64, win-x64, osx-x64, linux-arm64, win-arm64, osx-arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish
        run: dotnet publish -c Release -r ${{ matrix.rid }} --self-contained true -o publish/${{ matrix.rid }}

      - name: Upload published binaries
        uses: actions/upload-artifact@v4
        with:
          name: published
          path: publish